version: "3"

services:
    ansible:
        image: kabaconde/ansible-docker:deployment
        working_dir: /ansible
        volumes:
            - ./playbooks:/ansible
            - ~/.ssh/azure.pem:/tmp/.ssh/azure.pem:ro
        command: tail -f /dev/null && /bin/mount-ssh.sh
        environment:
            ANSIBLE_STDOUT_CALLBACK: debug
