---
- name: Create and start apache-deploy service
  docker_compose: # change this to docker container as import tasks
    project_src: "{{ local_project_root }}"
    restarted: yes
    state: present
    services:
      - apache-deploy
  tags:
    - dc_working_dir

- name: Add "{{ deploy_container_name }}" container to inventory
  add_host:
    name: "{{ deploy_container_name }}"
    ansible_connection: docker
    ansible_docker_extra_args: "-H=tcp://{{docker_forward_socket_host}}:{{ docker_forward_socket_port }}"
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python
  changed_when: false
  tags:
    - dc_working_dir
