---
- name: "Ensures {{ site }} dir exists"
  file:
    path: "{{ local_project_root }}"
    state: directory

- name: "Creating {{ site }} symfony.yml file"
  template:
    src: symfony.yml.j2
    dest: "{{ local_project_root }}/symfony.yml"

# https://stackoverflow.com/questions/41667864/can-the-templates-module-handle-multiple-templates-directories
- name: Ensure directory structure exists - (Docker-Compose Directories)
  file:
    path: "{{ local_project_root }}/{{ item.path }}"
    state: directory
    group: "{{ web_group }}"
    owner: "{{ web_user }}"
  with_filetree: "{{ docker_compose_templates_source }}"
  when: item.state == 'directory'

- name: Ensure files are populated from templates - (Docker-Compose Files)
  template:
    src: "{{ item.src }}"
    dest: '{{ local_project_root }}/{{ item.path | regex_replace("\.j2$", "") }}'
    group: "{{ web_group }}"
    owner: "{{ web_user }}"
  with_filetree: "{{ docker_compose_templates_source }}"
  when: item.state == 'file'

- name: Deploy symfony
  docker_stack:
    state: present
    name: "{{ site_formatted }}"
    compose:
      - "{{ local_project_root }}/symfony.yml"
  register: "deploy_symfony_output"

# - name: "Deploy symfony {{ site }}"
#   shell: "docker stack deploy --compose-file {{ local_project_root }}/symfony.yml {{ site_formatted }}"
#   register: "deploy_symfony_output"

- name: "Print create and start {{ site }}"
  debug:
    var: "deploy_symfony_output"
