---
- name: "Kill previous sessions on local port"
  delegate_to: localhost
  shell: ps axuf | grep {{ docker_forward_socket_port }} | grep ssh | awk '{print "kill -9 " $1}'

- name: Create SSH tunnel for docker socket forwading
  delegate_to: localhost
  shell: ssh -i {{ hostvars[inventory_hostname].ansible_ssh_private_key_file }} \
            -fNL {{ docker_forward_socket_host }}:{{ docker_forward_socket_port }}:/var/run/docker.sock \
            {{ hostvars[inventory_hostname].ansible_ssh_user }}@{{ inventory_hostname }} -v
  when: ssh_start
