---
- name: "Kill previous sessions on local port"
  delegate_to: localhost
  shell: ps axuf | grep {{ docker_forward_socket_port }} | grep ssh | awk '{print "kill -9 " $1}'

- name: Create SSH tunnel for docker socket forwading
  delegate_to: localhost
  shell: ssh -fNL {{ docker_forward_socket_host }}:{{ docker_forward_socket_port }}:/var/run/docker.sock deployer@{{ hostvars[inventory_hostname].inventory_hostname }} -v
  when: ssh_start
