my_sites:
  prod.dev.kabaconde.com:
    app_image: kabaconde/plaza:api-prod
    env:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: f96c2d666ace1278ec4c9e2304381bc3
      DATABASE_HOST: "db_{{ env }}"
      DATABASE_VERSION: "8"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "root"
      DATABASE_NAME: "plazadiamant_{{ env }}"
      DATABASE_PASSWORD: "{{ vault.db_passwords.mysql_password | urlencode() }}"
      DATABASE_URL: "mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=${DATABASE_VERSION}"
      MAILER_URL: null://localhost
      HOUSING_JSON_PATH: resources/housing
