---
- name: Install public assets
  delegate_to: "{{ deploy_container_name }}"
  shell: "bin/console assets:install --symlink public"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  ignore_errors: no

- name: Clear application cache
  delegate_to: "{{ deploy_container_name }}"
  shell: "bin/console cache:clear"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  ignore_errors: no

- name: Warmup application cache
  delegate_to: "{{ deploy_container_name }}"
  shell: "bin/console cache:warmup"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  ignore_errors: no
